### PR TITLE
fix: java.lang.IllegalArgumentException missing provider

### LINKED ISSUE #189: Fix java.lang.IllegalArgumentException: missing provider
Currently, Datasafe requires manual addition of BouncyCastle when Keystore modification operations are not called:
`Security.addProvider(new BouncyCastleProvider());`
we need to fix that - this should not be required

### PR DESCRIPTION
**Pull request by AssahBismarkabah**
Ensure that the `BouncyCastleProvider` is automatically added to the Security providers list, removing the need for manual intervention and preventing `IllegalArgumentException` errors related to missing provider.

### CODE REVIEW

File: datasafe-encryption/datasafe-encryption-impl/src/main/java/de/adorsys/datasafe/encrypiton/impl/utils/ProviderUtils.java [hunk 1]
```diff
@@ -1,5 +1,6 @@
 package de.adorsys.datasafe.encrypiton.impl.utils;
 
+import de.adorsys.keymanagement.adapter.modules.generator.GeneratorModule_ProviderFactory;
 import lombok.experimental.UtilityClass;
 import org.bouncycastle.jce.provider.BouncyCastleProvider;
```
Comment (max402) [inline datasafe-encryption/datasafe-encryption-impl/src/main/java/de/adorsys/datasafe/encrypiton/impl/utils/ProviderUtils.java]: Remove unused imports

File: datasafe-encryption/pom.xml [hunk 2]
```diff
@@ -15,4 +15,11 @@
         <module>datasafe-encryption-api</module>
         <module>datasafe-encryption-impl</module>
     </modules>
+    <dependencies>
+        <dependency>
+            <groupId>de.adorsys.keymanagement</groupId>
+            <artifactId>bouncycastle-adapter</artifactId>
+            <version>0.0.11</version>
+        </dependency>
+    </dependencies>
```
Comment (max402) [inline datasafe-encryption/pom.xml]: this dependency is not needed

**Review by max402 — APPROVED** [review]
